server:
  port: 8000
spring:
  application:
    name: dynamo-app
    hikari:
      # 30 秒, 心跳检测
      keepalive-time: 30000
      # 300 分钟, 连接最大存活时间
      max-lifetime: 18000000
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/code-dynamo?serverTimezone=GMT%2B8&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 123456

  #静态资源加载配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  quartz:
    # 持久化方式
    job-store-type: jdbc
    # 默认为false， 用于设定是否等待任务执行完毕后容器才会关闭。
    wait-for-jobs-to-complete-on-shutdown: false
    #定时任务启动开关，true-开  false-关
    auto-startup: true
    #启动时更新己存在的Job, 默认为false， 配置的JOB是否覆盖已经存在的JOB信息
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            # 集群名，区分同一系统的不同实例，若使用集群功能，则每一个实例都要使用相同的名字
            instanceName: quartzScheduler
            # 若是集群下，每个instanceId必须唯一
            instanceId: AUTO
          threadPool:
            #一般使用这个便可
            class: org.quartz.simpl.SimpleThreadPool
            #线程数量，不会动态增加
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    startup-delay: 1


# 自定义配置信息
dynamo:
  common:
    swagger:
      enabled: true
      author: dynamo
      version: 0.0.1
      title: dynamo项目
      description: code-dynamo项目
      # basic认证
      basic:
        enable: true
      base-packages:
        "[身份识别和管理]":
          - com.shaw.iam
        "[认证与权限]":
          - com.shaw.auth
        "[文件管理]":
          - com.shaw.file
        "[参数与数据字典]":
          - com.shaw.sys
    exception:
      # 显示详细异常
      show-full-message: true
    # 认证
    cache:
      # 默认超时时间 30分钟
      default-ttl: 1800
      # 对Key设置超时间 (秒)
      keys-ttl:
        "[iam:user:path]": 5200
        "[iam:ignore:path]": 28800
        "[iam:user:perm:code]": 28800
  kernel:
    auth:
      default-password: 123456
      ignore-urls:
        - '/actuator/**'
        - '/v3/api-docs/**'
        - '/doc.html'
        - '/swagger-resources/**'
        - '/token/**'
        - '/ws/**'
        - '/test/**'
        - '/webjars/**'
        - '/css/**'
        - '/error'
        - '/favicon.ico'
        - '/**'
